// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.Data;

namespace Sample.Data.Migrations
{
    [DbContext(typeof(SampleContext))]
    [Migration("20180829231104_OwnerNameRequired")]
    partial class OwnerNameRequired
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sample.Core.Domain.Automotive.Vehicle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Condition")
                        .HasMaxLength(10);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description");

                    b.Property<string>("ExteriorColor")
                        .HasMaxLength(25);

                    b.Property<string>("ImageTag")
                        .HasMaxLength(2083);

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2083);

                    b.Property<bool>("IsDeleted");

                    b.Property<long>("OwnerId");

                    b.Property<string>("Price")
                        .HasMaxLength(25);

                    b.Property<string>("SalePrice")
                        .HasMaxLength(25);

                    b.Property<string>("StateOfVehicle")
                        .HasMaxLength(4);

                    b.Property<string>("Title")
                        .HasMaxLength(100);

                    b.Property<string>("Url")
                        .HasMaxLength(2083);

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("Sample.Core.Domain.Owner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Owner");

                    b.HasData(
                        new { Id = 1L, CreatedOn = new DateTime(2018, 8, 21, 17, 0, 0, 0, DateTimeKind.Utc), IsDeleted = false, Name = "Joe" }
                    );
                });

            modelBuilder.Entity("Sample.Core.Domain.Automotive.Vehicle", b =>
                {
                    b.HasOne("Sample.Core.Domain.Owner", "Owner")
                        .WithMany("Vehicles")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Sample.Core.ValueObjects.Geometry", "Geometry", b1 =>
                        {
                            b1.Property<long?>("VehicleId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<double>("Lat");

                            b1.Property<double>("Lng");

                            b1.ToTable("Vehicle");

                            b1.HasOne("Sample.Core.Domain.Automotive.Vehicle")
                                .WithOne("Geometry")
                                .HasForeignKey("Sample.Core.ValueObjects.Geometry", "VehicleId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Sample.Core.ValueObjects.Vehicles.Automobile", "Automobile", b1 =>
                        {
                            b1.Property<long?>("VehicleId1")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Availablity")
                                .HasMaxLength(12);

                            b1.Property<string>("BodyStyle")
                                .HasMaxLength(12);

                            b1.Property<string>("DriveTrain")
                                .HasMaxLength(10);

                            b1.Property<string>("FuelType")
                                .HasMaxLength(10);

                            b1.Property<string>("Make")
                                .HasMaxLength(25);

                            b1.Property<string>("Model")
                                .HasMaxLength(25);

                            b1.Property<string>("Transmission")
                                .HasMaxLength(10);

                            b1.Property<string>("VehicleId")
                                .HasMaxLength(100);

                            b1.Property<string>("Vin")
                                .HasMaxLength(17);

                            b1.Property<int>("Year");

                            b1.ToTable("Vehicle");

                            b1.HasOne("Sample.Core.Domain.Automotive.Vehicle")
                                .WithOne("Automobile")
                                .HasForeignKey("Sample.Core.ValueObjects.Vehicles.Automobile", "VehicleId1")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Sample.Core.ValueObjects.Vehicles.Mileage", "Mileage", b1 =>
                        {
                            b1.Property<long?>("VehicleId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Unit")
                                .HasMaxLength(2);

                            b1.Property<int>("Value");

                            b1.ToTable("Vehicle");

                            b1.HasOne("Sample.Core.Domain.Automotive.Vehicle")
                                .WithOne("Mileage")
                                .HasForeignKey("Sample.Core.ValueObjects.Vehicles.Mileage", "VehicleId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
